name: Nuxt Generate / Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run generate --if-present
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: ftp://ftp.techherd.co:21/
        # FTP account username
        ftp-username: deployuser
        # FTP account password
        ftp-password: Ndh34kd8!@djs
        # The local folder to copy, defaults to root project folder
        local-dir: dist/
        # Passes through options into git-ftp
        git-ftp-args: --insecure
      env:
        CI: true
